authentication/urls.py
from django.urls import path
from . import views


app_name = "auth"


urlpatterns = [
    path("", views.login, name="login"),
    path("index/", views.index, name="index"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    # path("index/", views.index, name="index"),
    path("verify/", views.verify, name="verify"),
    path("location/", views.location, name="location"),
    path("upload/", views.upload_image, name="upload_image"),
    path("report/", views.view_images, name="report"),
]

web_rep_proj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("core/", include("core.urls")),
    path("", include("authentication.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    full_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True, blank=False, null=False)
    email = models.EmailField(max_length=50, unique=True, blank=False, null=False)
    password = models.CharField(max_length=100)
    profile = models.ImageField(upload_to="uploads/")
    result = models.ImageField(upload_to="uploads/")

    # USERNAME_FIELD = "email"
    # REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.full_name

core/models.py
from django.db import models


class UploadedImage(models.Model):
    image = models.ImageField(upload_to="uploads/")

core/forms.py
from django import forms
from .models import UploadedImage


class UploadedImageForm(forms.ModelForm):
    class Meta:
        model = UploadedImage
        fields = ["image"]

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth import authenticate, login as auth_login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Login View
def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return JsonResponse(
                {
                    "message": "Login successful",
                    "redirect_url": reverse("core:verify"),
                },
                status=200,
            )
        else:
            return JsonResponse({"message": "Invalid username or password"}, status=401)

    if request.headers.get("X-Requested-With") == "XMLHttpRequest":
        return JsonResponse({"message": "Method not allowed"}, status=405)

    return render(request, "pages/login.html")


# Profile View (Only Logged-in User Can See Their Data)
@login_required
def index(request):
    return render(request, "contents/index.html", {"user": request.user})

core/views.py
from django.shortcuts import render, redirect
from .models import UploadedImage
from .forms import UploadedImageForm


# index views
# @login_required
# def index(request):
#     return render(request, "contents/index.html", {"user": request.user})


def verify(request):
    return render(request, "pages/verify.html")


def location(request):
    return render(request, "pages/location.html")


def upload_image(request):
    pass


def view_images(request):
    images = UploadedImage.objects.all()
    return render(request, "pages/result.html", {"images": images})

templates/base.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 9]>
<html lang="en" class="no-js old-ie">
<![endif]-->
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="google" content="notranslate" />
    <title>{% block title %} - {% endblock title %}</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />

    <!-- CSS Files -->
    <link href="{% static 'css/boost.css' %}" rel="stylesheet" />
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav & Touch Icon -->
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'img/favicon.ico' %}?1"
    />

    <!-- JavaScript Files -->
    <script src="{% static 'js/jquery-1.8.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.inputmarks.js' %}"></script>
    <script src="{% static 'js/jquery.inputmark.ex.js' %}"></script>
    <script src="{% static 'js/jquery.selectCombo.js' %}"></script>
    <script src="{% static 'js/jquery.blockUI.min.js' %}"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    />

    <script>
      GUNCEL_SEZON = "2024-2025";
      GUNCEL_DONEM = "2";
    </script>

    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script
      type="text/javascript"
      src="{% static 'js/jqueryautocomplete.js' %}"
    ></script>
    <script
      type="text/javascript"
      src="{% static 'js/jquerybigframe.min.js' %}"
    ></script>
  </head>

  <body>
    {% block content %} {% endblock content %} {% load sweetify %} {% sweetify%}

    <!-- JavaScript Files -->
    <script src="{% static 'js/jquery-1.8.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.inputmarks.js' %}"></script>
    <script src="{% static 'js/jquery.inputmark.ex.js' %}"></script>
    <script src="{% static 'js/jquery.selectCombo.js' %}"></script>
    <script src="{% static 'js/jquery.blockUI.min.js' %}"></script>

    <script>
      GUNCEL_SEZON = "2024-2025";
      GUNCEL_DONEM = "2";
    </script>

    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script
      type="text/javascript"
      src="{% static 'js/jqueryautocomplete.js' %}"
    ></script>
    <script
      type="text/javascript"
      src="{% static 'js/jquerybigframe.min.js' %}"
    ></script>
  </body>
</html>

templates/contents/index.html
{% extends "base.html" %}

{% load static %}

{% block title %} OİS {% endblock title %}


{% block content %}

<body>
	<p id="back-top"><a href="#top"><i class="icon-chevron-up icon-2x"></i></a></p>
    	<nav style="margin-top: -20px;" class="sidr" id="sidr-left8"><span>Course Operations</span><a  href="/ogrenciler/ogrenci/slot">Slots</a><a  href="/dersler/dersprogrami/ogrindex">Course Schedule</a><a  href="/ogrenciler/derssecme/ogrindex">Course Registration</a><span style="height: 100px;">&nbsp;</span></nav><nav class="sidr" id="sidr-left7"><span>Documents</span><a  target=new  href="/ogrenciler/belge/transkript">Transcript</a><a  target=new  href="{% url 'core:report' %}">Report Card</a><a  target=new  href="/ogrenciler/belge/ogrdersprogrami">Course Program</a><a  target=new  href="/ogrenciler/belge/ogrpreptranskript">Prep Transcript</a><a  target=new  href="/hazirlik/hazirliksinav/ogrpreptranskript">Prep grade certificate</a><a  href="/ogrenciler/dilekce/duzenle">New Application Form</a><a  href="/ogrenciler/dilekce/liste">Application Forms</a><a  href="/ogrenciler/belgetalep/taleplerim">Online Document Request</a><a  target=new  href="/ogrenciler/belge/sinavprogrami">Examination Program</a><span style="height: 100px;">&nbsp;</span></nav><nav class="sidr" id="sidr-left9"><span>Other Settings</span><a  href="/ogrenciler/ogrenci/paroladegistirme">Change Password</a><a  target=new  href="http://gmail.com">E-Mail</a><a  href="/ogrenciler/anket/ogrindex">Surveys</a><a  href="/ogrenciler/belge/ogrtranskripthesap">GPA Calculator</a><a  href="/index/beyan/t/covid19asi">Covid 19 Vaccine Information</a><a  target=new  href="/fi/odeme/eodeme">e-Payment</a><a  href="/fi/odeme/ogrenci">Financial İnformation</a><a  href="/fi/iadetalep/ogrenciiadetalep">Financial Affairs Petition</a><a  href="/index/anlasma">Update Information</a><span style="height: 100px;">&nbsp;</span></nav><div class="navbar-left">
                    <ul class="sortable list"><li class="r3"><a id="left-menu8" href="#sidr-left8"><i class="icon-book icon-2x"></i></a></li><li class="r7"><a id="left-menu7" href="#sidr-left7"><i class="icon-file icon-2x"></i></a></li><li class="r8"><a id="left-menu9" href="#sidr-left9"><i class="icon-th icon-2x"></i></a></li></ul></div>	<div class="navbar navbar-fixed-top" >
			<div style="margin-top: -8px;"  class="navbar-inner gray-back align"
                            >

                    <a href="/" class="brand">
                        <img style="margin-left: 70px;" src="{% static 'img/auth_min_logo.png' %}">

                        					<span>Ois</span></a>
                                <div class="main-search center dropdown" style=" margin-bottom: 0px; margin-top: -30px;">
							<input  type="text" class="input-xxlarge ara dropdown-toggle" id="uygulama_ara" role="menu" aria-labelledby="dLabel" placeholder="Search Application ..." data-toggle="dropdown">
							<button type="button" class="ara-button" onclick="uygulamaAra()"><i class="icon-search"></i></button>
							<ul id="uygulama_ara_sonuc" class="dropdown-menu ara" role="menu"></ul>
  					</div>
                                <div class="session" id="session_countdown"><i class="fa fa-clock"></i>
                                    <b class="timer"></b> remains for your session timeout</div>
    <div class="user-info" style="height: 60px;">
  						<ul class="pull-left">  
						<li><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-chevron-down"></i> {% if request.user.is_authenticated %}
                            <img src="{{ request.user.profile.url }}" alt="Profile Image" 
                                 style="width: 90px; height: auto; border-radius: 50%;" />
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                                <li><p>{{ request.user.full_name }}</p></li>
                            </ul>
                        {% else %}
                            <p>Please log in</p>
                        {% endif %}
                        
</div>
	<div class="main">
        <div id="container" class="transitions-enabled clearfix main-margin">
            {% load static %}

<div class="dashboard-container">
    <!-- Announcements -->
    <div class="dashboard-box">
        <h3>Announcements</h3>
        <ul>
            <li><i class="fa fa-bullhorn"></i> <strong>2024-11-04</strong> MS Teams user login information document</li>
            <li><i class="fa fa-bullhorn"></i> <strong>2024-10-16</strong> Regulations</li>
            <li><i class="fa fa-bullhorn"></i> <strong>2024-08-21</strong> Yönetmenlikler</li>
            <li><i class="fa fa-bullhorn"></i> <strong>2024-08-09</strong> Online Document Request</li>
            <li><i class="fa fa-bullhorn"></i> <strong>2020-02-18</strong> Application Forms</li>
        </ul>
    </div>

    <!-- Distance Learning -->
    <div class="dashboard-box">
        <h3>Distance Learning</h3>
        <p><strong>Microsoft Teams</strong><br>
            Username: usaminu.cyp@bahcesehir.edu.tr<br>
            Password: OIS password
        </p>
        <img src="{% static 'img/ms_teams.png' %}" width="100" height="100" alt="Its Learning" class="learning-img">
        <button class="ms-teams-btn">Microsoft Teams</button>
    </div>

    <!-- Inbox -->
    <div class="dashboard-box">
        <h3>Inbox</h3>
        <ul>
            <li><i class="fa fa-envelope"></i> Inbox <span class="msg-count">2</span></li>
            <li><i class="fa fa-paper-plane"></i> Outbox</li>
            <li><i class="fa fa-edit"></i> Compose Message</li>
        </ul>
    </div>

    <!-- Courses -->
    <div class="dashboard-box">
        <h3>Courses</h3>
        <p>
            <i class="fa fa-user"></i> Advisor: <strong>ABDALLAH EL MOHAMED MERHEBI</strong><br>
            <i class="fa fa-envelope"></i> abdallah.merhebi@baucyprus.edu.tr
        </p>
        <div class="semester-box">Fall Dönemi Dersleri</div>
        <ul class="course-list">
            <li><i class="fa fa-folder"></i> MAT1051 Calculus I <span class="cms-badge">CMS</span></li>
            <li><i class="fa fa-folder"></i> PHY1001 Physics I <span class="cms-badge">CMS</span></li>
            <li><i class="fa fa-folder"></i> MAT1051 Calculus I <span class="cms-badge">CMS</span></li>
            <li><i class="fa fa-folder"></i> PHY1001 Physics I <span class="cms-badge">CMS</span></li>
            <li><i class="fa fa-folder"></i> PHY1001 Physics I <span class="cms-badge">CMS</span></li>
            <li><i class="fa fa-folder"></i> PHY1001 Physics I <span class="cms-badge">CMS</span></li>
        </ul>
    </div>
</div>

<!-- CSS Styles -->
<style>
    /* Remove unwanted background */
    body {
        background: white !important; /* Ensures a clean background */
        margin: 0;
        padding: 0;
    }

    .dashboard-container {
        display: flex;
        flex-wrap: wrap;
        gap: 20px;
        justify-content: center;
        align-items: flex-start;
        padding: 20px;
    }

    .dashboard-box {
        background: white;
        width: 320px; /* Increased width */
        height: 250px; /* Increased height */
        border-radius: 8px;
        padding: 15px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);
        overflow-y: auto; /* Enables vertical scrolling */
        overflow-x: hidden; /* Prevents horizontal scroll */
        color: #111; /* Dark text for readability */
        scrollbar-width: thin; /* Thin scrollbar */
        scrollbar-color: #666 #ddd; /* Custom scrollbar colors */
    }

    /* Custom scrollbar for Webkit browsers */
    .dashboard-box::-webkit-scrollbar {
        width: 8px;
    }

    .dashboard-box::-webkit-scrollbar-thumb {
        background: #666;
        border-radius: 4px;
    }

    .dashboard-box::-webkit-scrollbar-track {
        background: #ddd;
    }

    .dashboard-box h3 {
        background: #2c3237;
        color: white;
        padding: 10px;
        text-align: center;
        border-radius: 5px;
        font-size: 18px;
    }

    .dashboard-box ul {
        list-style: none;
        padding: 0;
    }

    .dashboard-box ul li {
        padding: 8px 0;
        font-size: 16px;
        color: #222; /* Dark text for readability */
    }

    /* Make icons darker */
    .dashboard-box i {
        color: #444; /* Darker icon color */
        margin-right: 5px;
    }

    .learning-img {
        width: 100%;
        height: auto;
        margin-top: 10px;
    }

    .ms-teams-btn {
        background: #0078d4;
        color: white;
        width: 100%;
        padding: 10px;
        border: none;
        margin-top: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    .semester-box {
        background: #ddd;
        padding: 10px;
        margin: 10px 0;
        font-size: 16px;
        font-weight: bold;
        color: #222; /* Dark text */
    }

    .cms-badge {
        background: #e0e0e0;
        padding: 4px 10px;
        border-radius: 5px;
        font-size: 14px;
        margin-left: 10px;
        font-weight: bold;
        color: #111;
    }

    .msg-count {
        background: red;
        color: white;
        padding: 5px 8px;
        border-radius: 50%;
        font-size: 14px;
        margin-left: 5px;
    }

    /* Positioning the Courses box to the right */
    .dashboard-box:nth-child(4) {
        margin-left: auto; /* Moves "Courses" to the right */
    }
</style>


<!-- FontAwesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

            
<script type="text/javascript" >
<!--
$(document).ready(function(){

	$("span.duyuru_konu").toggle(function(){
		$(this).parent().find("div").show("fast");
	},function(){
		$(this).parent().find("div").hide("fast");
	});


	$(window).bind('resize', function() {

	});
});
//-->
</script>
        </div>
	</div>
	</div>

    <script>
    $(function(){
                        widgetYukle('mesajkutusu');
                widgetYukle('uzaktanegitim');
                widgetYukle('dersler');
                widgetYukle('yazokulutalep');
                widgetYukle('duyurular');
                widgetYukle('yazokulutalep');
                widgetYukle('yazokulutalep');
                widgetYukle('yazokulutalep');
                widgetYukle('yazokulutalep');
                        startSessionCountdown(1800);
    });
    var BASE_URL='';
    var WIDGETS=[];
    
    
</script>
</body>

{% endblock content %}

templates/pages/location.html
{% extends "base.html" %} {% load static %} {% block title %} location
{%endblock title %}

<!-- body content -->

{% block content %}

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner align">
    <div class="fifty">
      <h1><a href="/">Bahçeşehir Cyprus University | OİS</a></h1>
    </div>

    <div class="fifty text-right">
      <div class="closeit pull-right">
        <a href="/"><i class="icon-remove-circle"></i></a>
      </div>
      <div id="session_countdown" class="direct pull-right">
        <span class="timer">20</span> seconds in you will be redirected
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="text-center">
    <a href="#">
      <h2>Bahcesehir University</h2>
      <h3>World Wide</h3>
    </a>
  </div>
  <style>
    .responsive-img {
      max-width: 100%;
      height: auto;
      display: block;
      margin: 0 auto;
    }
  </style>
  <!--<a target="_blank" href="https://bauglobal.com/recent-programs/"><img src="/img/bau-global-tr.jpg?2" alt=""></a>-->
  <a target="_blank" href="https://bauglobal.com/recent-programs/">
    <img
      src="{% static 'img/bau-global-tr.jpg' %}"
      width="900"
      height="500"
      alt=""
      class="responsive-img"
    />
  </a>

  <!--<img src="/img/BAU_CYPRUS_sem.jpg?2" alt="">-->

  <!-- Java Scripts -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="js/boot.js"></script>
  <script type="text/javascript" src="/jscript/main"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      let countdownElement = document.querySelector(
        "#session_countdown .timer"
      );
      let countdownTime = parseInt(countdownElement.textContent); // Get initial countdown value

      function updateCountdown() {
        if (countdownTime > 0) {
          countdownTime--;
          countdownElement.textContent = countdownTime; // Update text content
        } else {
          window.location.href = "{% url 'auth:index' %}"; // Redirect when countdown reaches 0
        }
      }

      // Start countdown every second
      setInterval(updateCountdown, 1000);
    });
  </script>

  {% endblock content %}
</div>

templates/pages/login.html
{% extends "base.html" %} {% load static %} {% comment %} title {% endcomment %}
{% block title %} login {% endblock title %} {% comment %} body {% endcomment %}
{% block content %}

<div class="login-form">
  <form method="POST" id="loginForm" action="{% url 'auth:login' %}">
    {% csrf_token %}
    <div class="shaky" style="text-align: center">
      <img src="/static/img/auth_min_logo.png" />
    </div>
    <div class="shaky">
      <!-- user group section -->
      <div class="login-head">
        <label>User Group</label>
        <div
          class="btn-group"
          data-toggle="buttons-radio"
          style="display: flex; gap: 0px"
        >
          <button
            type="button"
            class="btn tip2 og active"
            style="flex: 1"
            onclick="$('#userType').val(2);$('.tip2').show();$('.pass-reset.tip1').hide();$('.show2').show();$('.show1').hide()"
          >
            Student
          </button>
          <button
            type="button"
            class="btn tip1 pe"
            style="flex: 1"
            onclick="$('#userType').val(1);$('.pass-reset.tip1').show();$('.pass-reset.tip2').hide();$('.show1').show();$('.show2').hide()"
          >
            Staff
          </button>
        </div>
      </div>
      <div class="clearfix"></div>
      <div>
        <input type="hidden" id="userType" name="userType" value="2" />
        <label class="show1" style="display: none">User Name</label>
        <label class="show2">Username</label>
        <input
          type="text"
          class="input-xlarge"
          id="username"
          name="username"
          required
        />

        <style>
          .password-wrapper {
            display: flex;
            align-items: center;
            gap: 5px; /* Adjust the spacing between input and icon */
          }

          .password-wrapper input {
            width: 250px; /* Matches your original input width */
            height: 40px;
            border: 1px solid #ccc;
            border-radius: 5px;
            padding-left: 10px;
            font-size: 16px;
          }

          .password-wrapper i {
            font-size: 22px;
            color: #333;
            cursor: pointer;
          }
        </style>

        <label>Password</label>
        <div class="password-wrapper">
          <input
            type="password"
            class="input"
            id="password"
            name="password"
            required
          />
          <i onclick="togglePassword()" class="icon-eye-open"></i>
        </div>

        <script>
          function togglePassword() {
            var passwordField = document.getElementById("password");
            if (passwordField.type === "password") {
              passwordField.type = "text";
            } else {
              passwordField.type = "password";
            }
          }
        </script>

        <div class="clearfix"></div>
        <br />
        <button type="submit" class="btn btn-large btn-success shake">
          Login
        </button>
      </div>
      <div class="clearfix"></div>
      <br />
      <div class="align-left pass-reset tip2">
        <a
          class="active"
          data-toggle="modal"
          data-target="#passwordReset2"
          href="/sistem/sifrehatirlatma/index/type/2/ln/en"
          >Forgot Password</a
        >
      </div>
      <div class="align-left pass-reset tip1" style="display: none">
        <a
          class="active"
          data-toggle="modal"
          data-target="#passwordReset"
          href="/sistem/sifrehatirlatma/index/type/1/ln/en"
          >Forgot Password</a
        >
      </div>
      <div class="align-right text-right">
        Change Language<br />
        <div class="lang">
          <div
            class="btn-group"
            data-toggle="buttons-radio"
            style="display: flex"
          >
            <button
              type="button"
              class="btn tr"
              style="background-color: transparent; border: none"
              onclick="location.href='/auth/login/ln/tr'"
            >
              TR
            </button>
            <button
              type="submit"
              id="btn-login"
              class="btn en active"
              style="background-color: black; color: white; border: none"
              onclick="location.href='/auth/login/ln/en'"
            >
              EN
            </button>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>

<div
  id="passwordReset"
  class="login modal hide fade"
  tabindex="-1"
  role="dialog"
  aria-labelledby="myModalLabel"
  aria-hidden="true"
>
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
    <i class="icon-remove"></i>
  </button>
  <div class="modal-body" id="passwordReminder"></div>
</div>
<div
  id="passwordReset2"
  class="login modal hide fade"
  tabindex="-1"
  role="dialog"
  aria-labelledby="myModalLabel"
  aria-hidden="true"
>
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
    <i class="icon-remove"></i>
  </button>
  <div class="modal-body" id="passwordReminder"></div>
</div>
<script>
  $(document).on("submit", "#loginForm", function (e) {
    e.preventDefault();

    $(".alert").remove(); // Remove old alerts

    $.ajax({
      type: "POST",
      url: '{% url "auth:login" %}', // Ensure this matches the URL pattern in Django
      data: {
        username: $("#username").val(), 
        password: $("#password").val(),
        csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
      },
      dataType: "json",
      success: function (response) {
        let alertDiv = $();
        alertDiv.insertBefore("#loginForm");

        setTimeout(() => {
          window.location.href = response.redirect_url; 
        }, 1000);
      },
      error: function (xhr) {
        let alertDiv = $(
          `<div class="alert alert-danger text-center" role="alert">${xhr.responseJSON.message}</div>`
        );
        alertDiv.insertBefore("#loginForm");

        setTimeout(() => {
          alertDiv.fadeOut(500, function () {
            $(this).remove();
          });
        }, 3000);
      },
    });
  });
</script>

{% endblock content %}

templates/pages/result.html
{% extends "base.html" %} {% load static %} 
<!--  -->
{% block title %} Report {% endblock title %} 
<!--  -->
{% block content %}
<div style="margin-top: 40px; margin-left: 10%">
  {% if request.user.result %}
  <img
    src="{{ request.user.result.url }}"
    alt="Result Image"
    style="width: 85%; height: 90vh"
  />
  {% else %}
  <p>No result image uploaded yet.</p>
  {% endif %}
</div>
<br /><br />
{% endblock content %}

templates/pages/verify.html
{% extends "base.html" %}

{% load static %}

{% block title %} verify {% endblock title %}


{% block content %}

    <body><br></br><br></br>
	    	<center><div><img border="0" src="/static/img/auth_min_logo.png" /></center>
	            <center><h2>BAHÇEŞEHİR CYPRUS UNIVERSITY</h2></center>
          <div class="baslik">Address verification picture.</div>
<div class="submit"><img src="/static/img/avatars_07.jpg"/></div>
    <div class="submit"><a href="{% url 'core:location' %}"><input type="button" value="Continue" onclick="window.location='/'"/></a></div>
<style>
    .baslik
    {
        width:100%;
        margin-top: 20px;
        position: relative;
        text-align: center;
        font-size: 16px;
    }
    .submit
    {
        position: relative;
        width:100%;
        text-align: center;
        clear:both;
        margin-top: 10px;
    }



{% endblock content %}